import type { ServerErrorCode } from '@clicker/protocol';

export const strings = {
  title: 'Clicker',
  tagline: 'Ten seconds. One button. Most clicks wins.',
  createRoom: 'Create room',
  room: 'Room',
  nameLabel: 'Your name',
  namePlaceholder: 'Anna',
  enter: 'Enter',
  changeName: 'Change name',
  waiting: 'Waiting for the host to start',
  players: 'Players',
  copyInvite: 'Copy invite link',
  copyHostLink: 'Copy host link',
  copied: 'Copied',
  start: 'Start',
  again: 'Play again',
  click: 'CLICK',
  getReady: 'Get ready',
  go: 'Go!',
  finished: 'Finished',
  you: 'You',
  leader: 'Leader',
  connecting: 'Connecting…',
  reconnecting: 'Reconnecting…',
  roundAborted: 'The round was interrupted. Start a new one.',
  nobodyClicked: 'Nobody clicked',
  wins: 'wins!',
  resultsHeaders: {
    rank: '#',
    name: 'Name',
    clicks: 'Clicks',
  },
  // Keyed by every code the server can send, so a new one fails the build instead of showing nothing.
  errors: {
    not_host: 'Only the host can start a round',
    not_joined: 'You are not in the room yet',
    wrong_phase: 'Not now',
    room_full: 'The room is full',
    invalid_message: 'The server did not understand that',
    bad_version: 'This tab is out of date. Reload the page.',
  } satisfies Record<ServerErrorCode, string>,
};
